sudo: false
language: php
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - "/^v?[0-9\\.]+/"
php:
- 7.2
- 7.0
env:
- WP_VERSION=latest WP_MULTISITE=0
- WP_VERSION=trunk WP_MULTISITE=0
before_script:
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- composer install
- npm install
- npm run build
script:
- export PATH="$HOME/.composer/vendor/bin:$PATH"
- bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
- composer global require "phpunit/phpunit=4.8.*|5.7.*"
- composer install
- npm install
- npm run build
script:
  - ls -al
after_success:
- sed -i -e "s/nightly/${TRAVIS_TAG}/" $(basename $TRAVIS_REPO_SLUG).php
- curl https://raw.githubusercontent.com/miya0001/auto-build/master/auto-build.sh
  | bash
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: z+oxp/vjLwgGI0e636T1LQ9Q8McSpDE3iHrH0mEPuEkrdBS9Gynvjs0OXY7ylLNNg+KJ5Ga7gADVLrJTYR0PA/i71tKFs8gpomh6eFOMT2Wv5fZmPc+yHKZYrz/dtVtA+XWmNGzYlI1AB7IP4lafG4Fll+8sUCmgW7RdEzMe3qUQKj8+QJIQ35kNK1zrQXKnOTnIQeGBDcCWwjWrbJZMpnSUSLPVrsx/NRTrJEZADY5562ZJWZg1kFtXnH9gtfH530ejQ6WYkVDtKxXadJfKrs86SesjL6viVGkYjXdCGCc+etytnaJhwLtXmIbpIMQt7myUfOEWwfCwKvD4lBVVjWFzCNbc4XgvRNfqRc86yppjT6ouAWSok8gOJd5t4pgQGP/bjyap6ZLnkQWtP6ErDdVc/ugd1yyy2qTqVKaDtt85xEmmDjmlZO1EcEY6Ij58s0mdhmqd67bTbs1D49aKox31COiFbcCZh4qnSCBX82NOOXAVjNB9CngZy3bpoHcUF2x3NjU5ts0C/sm0IQiy1hjGkwZQchXKZIPef0p34ZtfHA7ho4OycCfFob6Qgnou1r3Rr8UeJQMjybng3iWsLn0HbD2/pPW0TmU/k/hbkaLfJEJ8eiEBfrrc3IG+3+TKr5ja6UD4XPskXvrF0zg+hqlauRy+wFEVtBwXNjG97eE=
  file: '_gallery.zip'
  on:
    tags: true
    repo: miya0001/_gallery
